spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql

  rabbitmq:
    host: 192.168.99.100
    username: kc4kt4
    password: qwerty

  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: admin
    password: password
    hikari:
      maximum-pool-size: 20

logging:
  level:
    ru.kc4kt4: debug
